# Generated by Django 5.1.1 on 2024-10-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='mpesa_number',
            field=models.EmailField(blank=True, help_text='If the payment is made via Mpesa', max_length=254, null=True),
        ),
    ]
