# Generated by Django 5.1.1 on 2024-10-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schoolaccount_account_number_schoolaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolaccount',
            name='account_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolaccount',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolaccount',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolaccount',
            name='branch_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
