# Generated by Django 5.1.1 on 2024-10-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_schoolaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='on_payroll',
            field=models.BooleanField(default=False),
        ),
    ]
