# Generated by Django 5.1.1 on 2024-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payroll_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('supervisor', 'Supervisor'), ('director', 'Director')], default='manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
