# Generated by Django 5.1.1 on 2024-10-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_manager_role_alter_manager_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAuthenticationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Manager AuthenticationCode',
                'verbose_name_plural': 'Manager Authentication Codes',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_temp_manager',
            field=models.BooleanField(default=False),
        ),
    ]
