# Generated by Django 5.1.1 on 2024-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_managerauthenticationcodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='specialties',
        ),
        migrations.AddField(
            model_name='trainer',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
    ]
