# Generated by Django 5.1.1 on 2024-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_trainer_specialties_trainer_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
