# Generated by Django 5.1.1 on 2024-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_trainer_account_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
