# Generated by Django 5.1.1 on 2024-10-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='TrainerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainer')),
            ],
            options={
                'verbose_name': 'Trainer Skill',
                'verbose_name_plural': 'Trainer Skills',
            },
        ),
        migrations.AddField(
            model_name='trainer',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainer_skills', to='core.trainerskills'),
        ),
    ]
