# Generated by Django 5.1.1 on 2024-10-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_trainer_years_of_experience_trainerskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='trainer_skills', to='core.trainerskills'),
        ),
    ]
