# Generated by Django 5.1.1 on 2024-10-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='skills',
        ),
    ]
