# Generated by Django 5.1.1 on 2024-10-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_trainerskills_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerskills',
            options={'ordering': ['-created'], 'verbose_name': 'Trainer Skill', 'verbose_name_plural': 'Trainer Skills'},
        ),
    ]
