# Generated by Django 5.1.1 on 2024-11-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_trainerskills_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='hourly_rate',
            new_name='hours_worked',
        ),
    ]
