# Generated by Django 5.1.1 on 2024-11-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_hourly_rate_trainer_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
