# Generated by Django 5.1.1 on 2024-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_payslip_trainer_alter_payroll_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='allowances',
            field=models.ManyToManyField(blank=True, related_name='payslip_allowances', to='core.allowances'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='deductions',
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='deductions',
            field=models.ManyToManyField(blank=True, related_name='payslip_deductions', to='core.deductions'),
        ),
    ]
