# Generated by Django 5.1.1 on 2024-11-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_payslip_allowances_payslip_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='payment_method',
        ),
    ]
