# Generated by Django 5.1.1 on 2024-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_payslip_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
