# Generated by Django 5.1.1 on 2024-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
